### ISSUE TITLE
Add draw circle to Map Control

### ISSUE THREAD

**Issue by hnahoulder** [iamanvesh/mapbox-gl-draw-circle#19]
Hello,

I'm looking for how can I add the draw circle control to my map control.

I have this code

```
const draw = new MapboxDraw({
      displayControlsDefault: true,
      userProperties: true,
      defaultMode: 'draw_circle',
      modes: {
        ...MapboxDraw.modes,
        draw_circle  : CircleMode,
        drag_circle  : DragCircleMode,
        direct_select: DirectMode,
        simple_select: SimpleSelectMode
      }
    });
```

And when I switch to draw polygon, I can't switch to draw circle again because I don't have it in my Map control
![image](https://user-images.githubusercontent.com/10942570/76536813-20ab2c80-647d-11ea-9c39-914611270e21.png)

**Comment by nik736** [comment]
I have the same question, did you find a solution for this yet?

**Comment by ajithes111** [comment]
+1

**Comment by cosminv6u** [comment]
I used the solution of fxi from here https://github.com/mapbox/mapbox-gl-draw/issues/874 to customize your Draw bar however you want.

**Comment by iamanvesh** [comment]
This library doesn't add a new icon in the draw bar as this is an extension to the existing library by mapbox and not intended to be a replacement. You can add your own custom icon / drop-down depending on the UX and invoke the functions using click handlers. Please refer to [this sample](https://github.com/iamanvesh/mapbox-gl-draw-circle-test).
