### ISSUE TITLE
Errors updating to mapbox-gl-draw to 1.2.0

### ISSUE THREAD

**Issue by ecarrillo01** [iamanvesh/mapbox-gl-draw-circle#26]
In recently updated my project mapbox-gl-draw version to 1.2.0, but it causes me errors with mapbox-gl-draw-circle module because its currently using mapbox-gl 1.1.1 version

**Comment by daniel-hauser** [comment]
Checked locally, tests are failing with @mapbox/mapbox-gl-draw@1.2.0` and passing @mapbox/mapbox-gl-draw@1.1.1`
