### ISSUE TITLE
having a feature of Drawing circle with Hold and Drag instead of creating it with initial radius

### ISSUE THREAD

**Issue by rhushikeshSahaj** [iamanvesh/mapbox-gl-draw-circle#3]
This question is more from a feature of Leaflet draw library comparison. In that, you can draw a circle by hold and drag to decide center and radius of the circle. In this library's implementation, you have to draw the circle by specifying an initial radius and then change it to modify the circle radius. 

Is there a way to decide radius upfront instead of changing it afterward

**Comment by Haixiang6123** [comment]
Same problem here. The Gif in README shows the drag-and-change feature, but it's not working for this version.

**Comment by iamanvesh** [comment]
> This question is more from a feature of Leaflet draw library comparison. In that, you can draw a circle by hold and drag to decide center and radius of the circle.

There's an active [PR](#4) right now for this, but I see some issues. Will ask the OP to fix them and see.

> Is there a way to decide radius upfront instead of changing it afterward

The current circle mode allows you to pass the radius as an option while in `changeMode` function.

**Comment by iamanvesh** [comment]
@rhushikeshSahaj  @haixiang6123 Released a new version which has the ability to drag and drop a circle. Do check it out and let me know. Closing this issue for now.
