### ISSUE TITLE
draw_polygon and draw_circle can not use at the same time,they clashed.

### ISSUE THREAD

**Issue by linghuam** [iamanvesh/mapbox-gl-draw-circle#5]
I add some draw mode to my program, when user click one type, they can draw corresponding  shape on the map. But the 'draw_polygon' mode draw the same shape as 'draw_circle ' mode, can you tell me how to solve this conflicts?

```js
map.on('load', e => {
    // userProperties has to be enabled
    var draw = new MapboxDraw({
        modes: {
            ...MapboxDraw.modes,
            draw_circle: CircleMode,
            direct_select: DirectMode,
            simple_select: SimpleSelectMode,
            draw_rectangle: DrawRectangle,
            lots_of_points: LotsOfPointsMode
        },
        displayControlsDefault: false
    });

    // Add this draw object to the map when map loads
    map.addControl(draw);

    window.drawTypeHandler = function(type) {
        switch(type) {
            case 1: draw.changeMode('draw_point');break;
            case 2: draw.changeMode('draw_line_string');break;
            case 3: draw.changeMode('draw_polygon');break;
            case 4: draw.changeMode('draw_rectangle');break;
            case 5: draw.changeMode('draw_circle');break;
        }
    }
});
```

**Comment by iamanvesh** [comment]
@linghuam I can confirm that both polygon and circle work together simultaneously, as I am currently using this in one of my projects. I have a couple of quick questions for you

* Did you enable the `userProperties`?
* Did you import the select modes?
    * All 3 modes have to be imported for this mode to work.

```js
import { CircleMode, DirectMode, SimpleSelectMode } from 'mapbox-gl-draw-circle';

var draw = new MapboxDraw({
    userProperties: true,
    modes: {
        ...MapboxDraw.modes,
        draw_circle: CircleMode,
        direct_select: DirectMode,
        simple_select: SimpleSelectMode,
        draw_rectangle: DrawRectangle,
        lots_of_points: LotsOfPointsMode
    },
    displayControlsDefault: false
});
```

It would be helpful if you can provide the error logs, if any.

**Comment by kaseymccurdy** [comment]
I can confirm that i'm seeing this as well. 

Some notes:
- If i import these modules (but dont use them anywhere), im still unable to draw polygons.
- When I simply comment out the import of `CircleMode, DirectMode, SimpleSelectionMode`, I'm able to draw polygons.
- im seeing no errors in my console at all

Here's my config (with circles enabled):

```
import mapboxgl from 'mapbox-gl';
import MapboxDraw from '@mapbox/mapbox-gl-draw';
import { CircleMode, DirectMode, SimpleSelectMode } from 'mapbox-gl-draw-circle';
...
    const Draw = new MapboxDraw({
      defaultMode: props.defaultMode,
      userProperties: true,
      modes: {
        ...MapboxDraw.modes,
        draw_circle: CircleMode,
        direct_select: DirectMode,
        simple_select: SimpleSelectMode,
      },
      displayControlsDefault: false,
      controls: {
        polygon: true,
        trash: true,
      },
    });
````

And here's my config with it disabled, which enables polygons to work:

```
import mapboxgl from 'mapbox-gl';
import MapboxDraw from '@mapbox/mapbox-gl-draw';
// import { CircleMode, DirectMode, SimpleSelectMode } from 'mapbox-gl-draw-circle';
...
    const Draw = new MapboxDraw({
      defaultMode: props.defaultMode,
      userProperties: true,
      modes: {
        ...MapboxDraw.modes,
        // draw_circle: CircleMode,
        // direct_select: DirectMode,
        // simple_select: SimpleSelectMode,
      },
      displayControlsDefault: false,
      controls: {
        polygon: true,
        trash: true,
      },
    });
```

**Comment by iamanvesh** [comment]
@kaseymccurdy Yes, I've noticed the issue too. Working on the solution.

**Comment by iamanvesh** [comment]
@linghuam @kaseymccurdy  I've released a new version, do check it out and let me know if you are still facing this issue.

**Comment by kaseymccurdy** [comment]
> @linghuam @kaseymccurdy I've released a new version, do check it out and let me know if you are still facing this issue.

Im taking a look now...thank you so much! Ill let you know...

**Comment by kaseymccurdy** [comment]
I just tested this, and it works GREAT!  Thank you so much for your effort into making such a great plugin. 💯💯💯

**Comment by iamanvesh** [comment]
@kaseymccurdy You're welcome! I'll be closing out this issue now.
