### ISSUE TITLE
Switch between polygons and circle 

### ISSUE THREAD

**Issue by evan0065** [iamanvesh/mapbox-gl-draw-circle#7]
Hi, I am using both mapbox-gl-draw-circle and mapbox-gl-draw. 

I was curious to know if it is possible to switch between circles and polygons without having to alter any code to make it switch. For instance, you could make the polygon button draw a polygon while the marker button draws a circle. 

Does anyone know if this is possible? I'm open to any options. Thanks!

**Comment by iamanvesh** [comment]
@evan0065  Yes, it is possible, but there is an issue open right now (#5). Will hopefully be releasing a new version this week.

**Comment by evan0065** [comment]
@iamanvesh Awesome, thanks for working on a solution! Do you have an idea when this will be fixed?

**Comment by iamanvesh** [comment]
@evan0065 Done with most of the changes, will have to update the docs and write some unit tests. The new version should be up tomorrow.

**Comment by evan0065** [comment]
@iamanvesh Sounds good, thank you. I really appreciate the work you're doing with this repo, it's very useful!
