### ISSUE TITLE
Add circle programmatically

### ISSUE THREAD

**Issue by bashtian** [iamanvesh/mapbox-gl-draw-circle#9]
I would like to add a non editable circle with a specified lat/lon and radius programmatically and clicking on the circle should make it editable. 
Is this currently possible with this library?

**Comment by iamanvesh** [comment]
You'd have to pass geometry in the same format as specified in the README, and change the mode to `simple_select` by passing that particular feature's id in `featureIds` option. Please refer  to [this link](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md#changemodemode-string-options-object-draw) for more information.

**Comment by gyenabubakar** [comment]
@iamanvesh Could you add a code example, please?
